/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testing.tests;


import testing.tests.unit.DiceTest;
import testing.tests.unit.GameTest;

public class AllTests {

    public static void main(String[] args) {
        new GameTest().testGameWithPlayer1Win();
        new GameTest().testGameWithPlayer2Win();
        new GameTest().testGameWithNobodyWin();
        new DiceTest().testBounds();
    }

}
