/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exceptions;

import java.nio.file.Paths;

public class App {
    public static void main(String[] args) throws Exception {

        ServiceLayerWorker worker = new ServiceLayerWorker();

        // Case 1: обернуть и прокинуть ServiceLayerException
        System.out.println("Case 1");
        try {
            System.out.println("Case 1: do something ");
            worker.doSomethingWrapExceptions("b.txt");
        } catch (ServiceLayerException e) {
            System.out.println("Case 1: catch " + e.getClass().getSimpleName());
            e.printStackTrace();
        }

        System.out.println("-----------------------");

        // Case 2: подавить
        System.out.println("Case 2");
        System.out.print("Case 2: try do something - ");
        System.out.println(worker.tryDoSomethingSuppressException("a.txt")?"Success":"Failed");

        System.out.println("-----------------------");

        // Case 3: пропускать
        System.out.println("Case 3");
        System.out.println("Case 2: do something and passing exceptions");
        worker.doSomethingPassingExceptions("b.txt");
        System.out.println("Case 3: end");

    }
}
